version: "3.9"

services:
  frontend:
    build: .
    container_name: optativas-frontend
    ports:
      - "4000:80"  # Mapeia a porta 80 do container para 3000 do host
    restart: unless-stopped

